@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmM3MDM4MjkyOWI1YmMwNDJiMDFmOSIsImVtYWlsIjoicS50ZW1wZWxhYXJzQGdtYWlsLmNvbSJ9LCJpYXQiOjE2ODA2MzM5MjUsImV4cCI6MTY4MDYzNzUyNX0.gIowEC3yhPB335XP5zTffzCDEkASPIsaKr86Bx2te3k
### Register call
POST http://localhost:8080/auth/register
content-type: application/json

{
    "email": "q.tempelaars@gmail.com",
    "password": "password"
}

### Login call
POST http://localhost:8080/auth/login
content-type: application/json

{
    "email": "q.tempelaars@gmail.com",
    "password": "password"
}

### Validate
GET http://localhost:8080/validate
content-type: application/json
Authorization: Bearer {{TOKEN}}

### Profile
GET http://localhost:8080/profile/
content-type: application/json
Authorization: Bearer {{TOKEN}}

### Get all Targets
GET http://localhost:8080/target/
content-type: application/json
Authorization: Bearer {{TOKEN}}