@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MzE4MjkwMzVlY2I5MjQ1NmY1NGM3YSIsImVtYWlsIjoicXVpbkBnbWFpbC5jb20iLCJyb2xlcyI6WyJnZWJydWlrZXIiXX0sImlhdCI6MTY4MDk2Njk5OCwiZXhwIjoxNjgwOTcwNTk4fQ.5BY1pZ_MgMMHmMLzQONSOYtmqKFb-3i4YIAOCFPHB9A
@TARGET_ID = 642feb2fa31fd88bdc975cd7
### Register call
POST http://localhost:8080/auth/register
content-type: application/json

{
    "email": "quin@gmail.com",
    "password": "password"
}

### Login call
POST http://localhost:8080/auth/login
content-type: application/json

{
    "email": "quin@gmail.com",
    "password": "password"
}

### Validate
GET http://localhost:8080/validate
content-type: application/json
Authorization: Bearer {{TOKEN}}

### Profile
GET http://localhost:8080/profile/
content-type: application/json
Authorization: Bearer {{TOKEN}}

### Get all Targets
GET http://localhost:8080/target/
content-type: application/json
Authorization: Bearer {{TOKEN}}

### Get Target image
GET http://localhost:8080/target/{{TARGET_ID}}/image
content-type: application/json
Authorization: Bearer {{TOKEN}}

### Delete target
DELETE http://localhost:8080/target/{{TARGET_ID}}
content-type: application/json
Authorization: Bearer {{TOKEN}}

### Delete participant
DELETE http://localhost:8080/target/{{TARGET_ID}}/642feb43a31fd88bdc975cdc
content-type: application/json
Authorization: Bearer {{TOKEN}}