global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
    - targets: ["api-gateway:3000"]
  - job_name: "auth-service"
    static_configs:
    - targets: ["auth-service:3001"]
  - job_name: "profile-service"
    static_configs:
    - targets: ["profile-service:3002"]
  - job_name: "target-service"
    static_configs:
    - targets: ["target-service:3003"]
  - job_name: "db-exporter"
    static_configs:
    - targets: ["db-exporter:9216"]
  - job_name: "rabbitmq-exporter"
    static_configs:
    - targets: ["rabbitmq-exporter:3005"]